runtime: nodejs16

instance_class: F1

service: documentation-service

handlers:
  - url: /
    static_files: docs/.vitepress/dist/index.html
    upload: docs/.vitepress/dist/.*
    # script: auto
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    static_files: docs/.vitepress/dist/index.html
    upload: docs/.vitepress/dist/.*
    secure: always
    redirect_http_response_code: 301