runtime: nodejs16

instance_class: F1

service: documentation-service

handlers:
  - url: /
    # static_dir: docs/.vitepress/dist/index.html
    static_files: docs/.vitepress/dist/index.html
    upload: docs/.vitepress/dist/.*
    secure: always
    redirect_http_response_code: 301

  # - url: /(.*\.(js|css))$
  #   static_dir: docs/.vitepress/dist
  #   # static_files: docs/.vitepress/dist/\1
  #   # upload: www/(.*)
  #   secure: always
  #   redirect_http_response_code: 301

  - url: /(.*\.(js|css|html))$
    # static_dir: docs/.vitepress/dist
    static_files: docs/.vitepress/dist/\1
    upload: docs/.vitepress/dist/.*
    secure: always
    redirect_http_response_code: 301